;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayAbility.Cast.Fire.ContinueAbility",NewTagName="GameplayAbility.Cast.Sunstrike.ContinueAbility")
+GameplayTagRedirects=(OldTagName="GameplayAbility.Cast.Fire",NewTagName="GameplayAbility.Cast.Sunstrike")
+GameplayTagRedirects=(OldTagName="GameplayCue.SummonMinions.SummonSound",NewTagName="GameplayCue.SummonMinions.Summon")
+GameplayTagList=(Tag="Character.State",DevComment="")
+GameplayTagList=(Tag="Character.State.Acceleration",DevComment="")
+GameplayTagList=(Tag="Character.State.Bleeding",DevComment="")
+GameplayTagList=(Tag="Character.State.Burning",DevComment="")
+GameplayTagList=(Tag="Character.State.Deceleration",DevComment="")
+GameplayTagList=(Tag="Character.State.Healing",DevComment="")
+GameplayTagList=(Tag="Character.Team.Blue",DevComment="")
+GameplayTagList=(Tag="Character.Team.Neutral",DevComment="")
+GameplayTagList=(Tag="Character.Team.Red",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Cast.SummonMinions",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Cast.Sunstrike.ContinueAbility",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Cooldown.SummonMinions",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Cooldown.Sunstrike",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ExplosionFire",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Pistol.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Pistol.Shot",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.RPG.ExplosionFire",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.RPG.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.RPG.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.RPG.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PickUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Pistol.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Pistol.Shot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RPG.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RPG.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RPG.ReloadEnd",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RPG.Shot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SummonMinions",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SummonMinions.Casting",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SummonMinions.Summon",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sunstrike",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sunstrike.Preview",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Damage.BodyOnly",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Damage.Full",DevComment="")
+GameplayTagList=(Tag="InputAction.Attack",DevComment="")
+GameplayTagList=(Tag="InputAction.Dash",DevComment="")
+GameplayTagList=(Tag="InputAction.PickUp",DevComment="")
+GameplayTagList=(Tag="InputAction.Reload",DevComment="")
+GameplayTagList=(Tag="InputAction.Shoot",DevComment="")
+GameplayTagList=(Tag="InputAction.SummonMinions",DevComment="")
+GameplayTagList=(Tag="Inventory.Item.Pistol",DevComment="")
+GameplayTagList=(Tag="Inventory.Item.RPG",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Duration.Burn",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Duration.Reload",DevComment="")
+GameplayTagList=(Tag="SetByCaller.ExperienceSet.Experience",DevComment="")
+GameplayTagList=(Tag="SetByCaller.ExperienceSet.Level",DevComment="")
+GameplayTagList=(Tag="SetByCaller.HealthSet.IncomingDamage",DevComment="")
+GameplayTagList=(Tag="SetByCaller.ManaSet.Mana",DevComment="")
+GameplayTagList=(Tag="SetByCaller.MovementSet.SpeedUp",DevComment="")

